### ISSUE TITLE
Posterior predictive assessment of model fitness

### ISSUE THREAD

**Issue by ji26** [vnminin/stoch_mod_journal_club#4]
[Posterior predictive assessment of model fitness](http://www.cs.princeton.edu/courses/archive/fall09/cos597A/papers/GelmanMengStern1996.pdf) -- scheduled for February 6.

**Comment by vnminin** [comment]
Some papers that use posterior predictive diagnostics in phylogenetics:

* [Mapping Mutations on Phylogenies](http://sysbio.oxfordjournals.org/content/51/5/729.short)
* [Stochastic Mapping of Morphological Characters](http://sysbio.oxfordjournals.org/content/52/2/131.short)
* [Fast, accurate and simulation-free stochastic mapping](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2607419/)
